name: "2026100501: Build curl-impersonate [target:i686]"

on:
  workflow_dispatch:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y gcc-i686-linux-gnu g++-i686-linux-gnu cmake ninja-build make patch binutils ca-certificates curl
          git clone --depth 1 https://github.com/lexiforest/curl-impersonate.git
          cd curl-impersonate
          git rev-parse HEAD
          make prepare-libidn2
          make build JOBS=1 CMAKE_CONFIGURE_ARGS="-DCMAKE_C_COMPILER=i686-linux-gnu-gcc -DCMAKE_CXX_COMPILER=i686-linux-gnu-g++ -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=i686 -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}"
